apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ravanan/argo-cd-deployment-with-eks.git
    targetRevision: feature/argocd-within-minikube
    path: k8s
  destination:
    server: https://31969E0B7C75652507863615975A512A.gr7.ap-southeast-2.eks.amazonaws.com
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
