apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ravanan/argo-cd-deployment-with-eks.git
    targetRevision: feature/argocd-within-minikube
    path: k8s
  destination:
    server: https://74319F3AE8FE2FA0A40E4B33EABD71C3.gr7.ap-southeast-2.eks.amazonaws.com
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
